name:                auth-server
version:             0.1.0.0
github:              "abailly/auth-server"
license:             BSD3
author:              "Arnaud Bailly"
maintainer:          "arnaud@pankzsoft.com"
copyright:           "2020 Arnaud Bailly"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A generic Servant-based authentication server
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/abailly/auth-server#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options: -Wall -Werror -fno-warn-orphans
default-extensions:
  - DataKinds
  - FlexibleContexts
  - MonoLocalBinds
  - MultiParamTypeClasses
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables
  - TypeOperators
  - NamedFieldPuns

library:
  dependencies:
    - aeson
    - async
    - base
    - bytestring
    - base64-bytestring
    - containers
    - cryptonite
    - data-default
    - free
    - freer-simple
    - http-client
    - jose
    - lens
    - mtl
    - network
    - random
    - servant
    - servant-auth
    - servant-auth-server
    - servant-auth-swagger
    - servant-server
    - servant-client
    - servant-server-base
    - servant-swagger
    - swagger2
    - template-haskell
    - text
    - time
    - wai
    - wai-extra
    - wai-cors
    - warp
  source-dirs: src

executables:
  hsauth:
    main:                server.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - auth-server
    - aeson
    - async
    - base
    - bytestring
    - containers
    - http-client
    - http-types
    - mtl
    - network
    - random
    - servant
    - servant-client
    - servant-server
    - stm
    - text
    - wai
    - wai-middleware-static
    - warp

tests:
  auth-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - auth-server
    - aeson
    - async
    - base
    - base64-bytestring
    - binary
    - bytestring
    - containers
    - cryptonite
    - directory
    - freer-simple
    - generic-random
    - hspec
    - hspec-core
    - hspec-discover
    - hspec-golden-aeson
    - hspec-wai
    - hspec-wai-json
    - http-client
    - http-conduit
    - http-types
    - jose
    - lens
    - mtl
    - network
    - process
    - protolude
    - QuickCheck
    - quickcheck-instances
    - safe-exceptions
    - scientific
    - servant
    - servant-auth
    - servant-auth-server
    - servant-client
    - servant-client-core
    - servant-server
    - silently
    - stm
    - template-haskell
    - text
    - unix
    - vector-instances
    - wai-extra
    - warp
